#!/bin/sh

echo -n "Enter your name: "

if read name
then
    if [ -n "$name" ]
    then
        echo "Hello, $name!"
    else
        echo "Hello, tmpuser?"
    fi
else
    echo
    echo "Hello, tmpuser?"
fi
